matrix:
  include:
    - os: linux
      language: generic
      dist: trusty
      sudo: required
      services:
        - docker
      script:
        - make test-linux-docker
    - os: osx
      language: objective-c
      osx_image: xcode10
      script:
        - make test
