name: Pathos
targets:
  Pathos:
    type: framework
    platform: macOS
    sources: Sources/Pathos
    scheme:
      gatherCoverageData: true
    settings:
      INFOPLIST_FILE: Resources/Info.plist
    configFiles:
      Release: Resources/release.xcconfig
