name: Ubuntu Bionic

on: [push, pull_request]

jobs:
  linux:
    name: Ubuntu Bionic
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - 5.3
        distro:
          - bionic
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: Scripts/docker.sh Pathos 'swift test -Xswiftc -warnings-as-errors' ${{ matrix.swift }} ${{ matrix.distro }}
